### ISSUE TITLE
old versions of allele model are not referenced from main page, but still generated

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/data-model-docs#11]
With recent UI updates, we are no longer linking to older versions of the allele model. However, they are still being generated-- for instance, you can get directly there at [http://datamodel.clinicalgenome.org/allele/0.1](http://datamodel.clinicalgenome.org/allele/0.1).

If we are OK with not showing earlier versions for now, then we could eliminate the builds of these earlier versions and speed up the build process.

Mostly just pointing this out for discussion. Potentially interested parties: @nafisakhandaker @sgoehringer @larrybabb @cbizon

**Comment by cbizon** [comment]
I think it would be fine to eliminate these builds.

**Comment by bpow** [comment]
Only @cbizon has commented, and he is OK with this, so I will go ahead and make the change for now. We can reconsider if we want to go back to generating the older doc versions.

**Comment by bpow** [comment]
No one having said anything to the contrary for ~0.5 years, I will close this issue.
