### ISSUE TITLE
All external links should open in new browser tab

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/data-model-docs#7]
@nafisakhandaker could you go through this, the allele and the interpretation documentation and make sure that all links to external sites (outside our datamodel.clinicalgenome.org domain) open new tabs versus replacing the current tab?

All internal links within our documentation should also be verified to open within the same browser tab/window.

As an example, the [Welcome page in the Interpretation model](http://datamodel.clinicalgenome.org/interpretation/) has a SEPIO link which replaces the current tab.  This should open a new tab.  But the link below it to the "ClinGen Allele Model" should simply navigate within the same tab.

**Comment by nafisakhandaker** [comment]
https://github.com/monarch-initiative/SEPIO-ontology/wiki
http://wiki.hl7.org/index.php?title=FHIR
https://github.com/clingen-data-model/allele --- None of the above links open in new tab. I will fix these and others as well.

**Comment by nafisakhandaker** [comment]
There is no such feature in markdown to open a link in new tab.
We have to use HTML inside markdown. Let me know if everyone is OK with it.

**Comment by bpow** [comment]
it's not standard markdown, but kramdown (which we use in middleman) can support this by changing something like:
```
[Monarch SEPIO](https://github.com/monarch-initiative/SEPIO-ontology/wiki)
```
to:
```
[Monarch SEPIO](https://github.com/monarch-initiative/SEPIO-ontology/wiki){:target="_blank"}
```

**Comment by bpow** [comment]
That being said, whether or not external links should open in new windows/tabs is a bit of a emacs vs. vi discussion-- with arguments from both sides. I tend to be of the camp that says that I have a way to open links in a new tab if I want to (right-click or ctrl-click), and am a bit annoyed when new tabs open that I didn't want to have open (which messes up my expected ability to navigate using the history, since the new tab's history is separated from the old tab.

But I'm not a zealot about this point.

**Comment by nafisakhandaker** [comment]
I could figure out how to fix the links using kramdown markdown and started to fix the links.

**Comment by sgoehringer** [comment]
@bpow @nafisakhandaker I should be able to take care of this via jquery if you like.

**Comment by nafisakhandaker** [comment]
I took care most of the link. I didn't close it if in case I find more
links to open on new window.
I think this one should be closed.

*Nafisa Khandaker*
Email: nafkhan@gmail.com Cell: 617-501-7745 <6175017745>
