### ISSUE TITLE
Review data-model-docs Branding Branch

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/data-model-docs#8]
Hello @larrybabb @cbizon @nafisakhandaker @bpow @tnavatar !I wrapped up the UI/UX updates for data-model-docs in a branch (https://github.com/clingen-data-model/data-model-docs/tree/BrandingQ42017) Take a look and let me know if you have any ideas/issues.

I brought in files from the clingen-static-resources so this build was able to run locally with what is needed.  I also moved the changes that I made here back into clingen-static-resources.  

@nafisakhandaker - The one item to note is to make it work correctly locally I needed to comment out the reference to the live static code (https://github.com/clingen-data-model/data-model-docs/blob/BrandingQ42017/config.rb#L65) because the CSS for testing was local.  Just so you know, I didn't remove these comment either (only because I wasn't sure if anyone on the team would want to build locally).  

Lets put a time on the calendar to sync up after things settle down after the release for variant work.  Thanks for all your work!

**Comment by nafisakhandaker** [comment]
@sgoehringer I saw your changes. I am OK with it. We will discus after things settle down .
Thanks.

**Comment by bpow** [comment]
Just a thought-- would it be reasonable to have clingen-static-resources as a git submodule and assets linked in that way? It seems awkward to have these resources in two different places. I definitely like having the repo being able to be served on its own without reference to the published static resources, though...

**Comment by nafisakhandaker** [comment]
I was thinking the same. I like the idea.

*Nafisa Khandaker*
Email: nafkhan@gmail.com Cell: 617-501-7745 <6175017745>

**Comment by sgoehringer** [comment]
Closing this general item out and starting one about "clingen-static-resources as a git submodule"... feel free to create issues based on specific needs.
